# Generated by Django 6.0.6 on 2026-06-24 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('number_of_days', models.IntegerField(default=1)),
                ('is_payment_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=12, null=True)),
                ('digital_access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
