# Generated by Django 6.0.6 on 2026-06-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_days',
            new_name='days_booked',
        ),
        migrations.RenameField(
            model_name='guestprofile',
            old_name='total_days_on_hotel',
            new_name='days_booked',
        ),
    ]
