# Generated by Django 6.0.6 on 2026-07-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_checkin_date_booking_days_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='days_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guestprofile'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('FAMILY', 'Family'), ('SINGLE', 'Single'), ('PRESIDENTIAL', 'Presidential')], default='STANDARD', max_length=20),
        ),
    ]
