# Generated by Django 6.0.6 on 2026-07-03 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_guestprofile_days_booked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroom',
            old_name='is_cleaned',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='days_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_profile',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.guestprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.hotelroom'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='user_name',
            field=models.CharField(default='Anonymous Guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0005923000987166831, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('DELUXE', 'Deluxe Room'), ('SUITE', 'Executive Suite'), ('STANDARD', 'Standard Room')], default='STANDARD', max_length=20),
        ),
    ]
