# Generated by Django 6.0.6 on 2026-07-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_room_payment_alter_accesslog_room_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_refunded',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refund_amount',
        ),
    ]
