# Generated by Django 6.0.6 on 2026-07-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_payment_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='digital_access_token',
        ),
    ]
